### ISSUE TITLE
Darkmode readability

### ISSUE THREAD

**Issue by stonewalljones** [deathworlders/online#104]
In Deathworlders 63 the email header is unreadable when the website's darkmode is enabled.

Here is the section that is unreadable:
https://github.com/deathworlders/online/blame/master/content/books/deathworlders/chapter-63-torn.md#L268-L280

Attached are screenshots of the issue.

![Screenshot from 2020-02-28 13-18-16](https://user-images.githubusercontent.com/6126541/75575019-57b92100-5a2d-11ea-8f42-1ad6bae4d76d.png)
![image](https://user-images.githubusercontent.com/6126541/75575041-669fd380-5a2d-11ea-91e1-03364c9ce7e7.png)

**Comment by operinko** [comment]
https://github.com/deathworlders/kiera/pull/10
