### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by Azimoth** [deathworlders/online#115]
Hi, 
I'm fairly new to the JVerse, but liked chapter 00 very much. In fact I liked it so much, I wanted to show it to friends of mine, who don't speak English well enough to read the original text. 
Are you aware of translated versions of your works?

Since I couldn't find anything so far, I wrote a translation of chapter 00 to german myself and I'm willing to share it, if you're interested. Do you see any use for that?

**Comment by ctwelve** [comment]
We are not aware of translated works, and our content license permits such things. We'd love to see what you've done!

**Comment by Azimoth** [comment]
Where would I paste/upload/send it? In what way/format preferably?

**Comment by ctwelve** [comment]
Well, I'm not sure, actually. We'd probably need to make a new folder for it entirely. Do you have Discord? That's the easiest way to talk to me and Hambone.

**Comment by Azimoth** [comment]
As a matter of fact I do. Where/How would I find you?

**Comment by ctwelve** [comment]
Join the HFY Discord! The link can be found on reddit
