### ISSUE TITLE
What do I need to make hugo build this thing?

### ISSUE THREAD

**Issue by tko** [deathworlders/online#116]
I've been reading the epub (awesome!) and spotting a few misspellings or html tags here and there. Discovered this repo and thought I could send some fixes. But I'm finding it difficult to reproduce the epub from here.

```bash
> hugo version
Hugo Static Site Generator v0.72.0/extended darwin/amd64 BuildDate: unknown
> git clone --recurse git@github.com:deathworlders/online.git deathworlders-online
[...]
> cd deathworlders-online
> hugo
Total in 274 ms
Error: Error building site: "/tmp/deathworlders-online/content/books/bolthole-aces/chapter-00-Prelude-to-War.md:1:1": plain HTML documents not supported
```
Ok, so that's some `<<< current === >>> before discard` merge conflict looking kind of thing. Deleting that book just to get it out of the way and trying again
```bash
> rm -rf content/books/bolthole-aces
> hugo
Building sites … WARN 2020/06/18 21:19:43 Page.Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2020/06/18 21:19:43 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
Total in 464 ms
Error: Error building site: failed to render pages: render of "section" failed: "/tmp/deathworlders-online/themes/kiera/layouts/_default/list.html:15:14": execute of template failed: template: _default/list.html:15:14: executing "main" at <.Paginate>: error calling Paginate: cannot convert type page.PagesGroup to Pages
```
I tried several older hugo versions but none made any difference.

I'm unfamiliar with hugo, is there a trick run it successfully?

**Comment by ctwelve** [comment]
Hi. We're actually using Hugo 0.48 I believe, because they made some grammar changes that broke a lot of our source. It's a long-term project to fix it but honestly, 90% of our effort is in writing the next chapter.

We specifically use Netlify to deploy our website in a sort of sideways-thinking application of CI. Hope this helps!

**Comment by tko** [comment]
Ha, nice timing. I was just about comment I found that it's the `content/books/deathworld-origins/_index.md` file that is breaking modern hugo for whatever reason and if you just move it elsewhere say, as `content/deathworld-origins.md` it's no longer a problem.

Also the bolthole-aces content between the conflict markers are identical, so just removing the markers and the duplicate content should be fine and the site builds again.

Not a problem. Did not mean to be a distraction.
