### ISSUE TITLE
Chapter 76: Epub Render error

### ISSUE THREAD

**Issue by issmirnov** [deathworlders/online#134]
I downloaded the default epub and opened it in Apple Books. The following error appeared:

![0484C8C1-7E40-41D2-A379-F7F9E1ED231F](https://user-images.githubusercontent.com/5771615/120049163-2724b600-bfe7-11eb-9525-0c2eff63254e.png)

**Comment by ctwelve** [comment]
Hello! We've done update work on that, can you give it a try?

**Comment by issmirnov** [comment]
Just checked, looks fixed! Thanks :)
