### ISSUE TITLE
Humans in chapter 91ff should remember some stuff from chapter 36...

### ISSUE THREAD

**Issue by wklaebe** [deathworlders/online#143]
WARNING, spoilers up to chapter 91 ahead, maybe!

So... humanity needs to relocate away from earth. Why not use those colonies seeded throughout the galaxy by the ColTainer project? Why settle Nightmare before even looking at those?

**Comment by ctwelve** [comment]
Coltainers were not well-addressed, but some chapters back that line of attack was ruled out by Lewis himself. Sorry! It's how web serials go: this is very much a first draft, for which we are now in the process of consolidating into novels...
