### ISSUE TITLE
Implement boilerplate

### ISSUE THREAD

**Issue by ctwelve** [deathworlders/online#15]
One of the things we need to do is have an About page, License, FAQ...and ideally links to other related projects around the web should be there, too.

* [ ] About Us page
* [ ] Related Projects page
* [ ] License page

**Comment by jaskij** [comment]
I learned about Hugo from deathworlders.com, now I'm learning Hugo by trying to improve this site (and yes, I love the books!).

License and About Us is mostly static text so once you send me the content it's not a problem (copy single-page theme without navigation footer, set URL in front-matter, done)

As for Related Projects - I propose to make a [data-driven page](https://gohugo.io/templates/data-templates/) - that is once the template is done you just describe those related pages in toml/yaml/json and Hugo does the rest (would need a discussion on fields in that description)

**Comment by jaskij** [comment]
I have two ideas on how to implement this, will choose the one easier on editors and submit a PR this week.
