### ISSUE TITLE
RSS articles pointing to index

### ISSUE THREAD

**Issue by HamboneHFY** [deathworlders/online#63]
Message received from a reader:

"Hi,

Just so you know, with the new site I can subscribe to the RSS feed but when I try selecting an article all I get is the feed page (http://deathworlders.com//index.xml) rather than the article page. This is using a Firefox 52 (I am blind and there is an accessibility problem using more recent releases)."

**Comment by Slord6** [comment]
Don't know if it's a new issue (if so happy to open one), or related to this, but the current RSS links are invalid as they should be absolute URLs, not relative. Think this is fixed by setting the baseURL in the config for Hugo sites
