### ISSUE TITLE
Chapter Titles for BoltHole aces and Deathworlders look similiar in Index

### ISSUE THREAD

**Issue by ghost** [deathworlders/online#64]
https://imgur.com/KfKUMJe

To a new user, if they entered the Deathworlders site and saw this, I think that they would believe that Chapter 00 and Chapter 45 are part of the same series, even though one is from Bolthole Aces and the other from Deathworlders.  Changing the wording of the chapter to Bolthole Aces: Chapter 00, and The Deathworlders: Chapter 45 would ease some of the confusion.

**Comment by tsanth** [comment]
I've jimmied a fix for this into the Kiera theme.

Behold: https://imgur.com/LN2uaxc
