### ISSUE TITLE
Chapter 39 Text missing

### ISSUE THREAD

**Issue by GregorL** [deathworlders/online#93]
Art least two spots in the chapter seem to be missing text: 
> [...]ost influential remaining candidate is Turan, of Ironclaw.
> 
> = , then. And had hitherto = =
> 
> The Entity ran a n[...]

And

> [...]disconnect carefully, leaving early but not alacritously.
> 
> had already been riding high in its list of priorities; There wasn’t [...]

**Comment by ctwelve** [comment]
Got it. I'm motoring through formatting fixes this weekend, we'll see how far I get.

**Comment by Krutonium** [comment]
Out of curiosity did this get finished?
