### ISSUE TITLE
epub formatting

### ISSUE THREAD

**Issue by Erroneous1** [deathworlders/online#95]
I combined all of Deathworlders chapters 0-51 into a single epub with embedded fonts and some fixed CSS. I also combined all of the sections in each chapter so you can have a single TOC instead of 1 for each chapter.

I'm a programmer and would love to automate this and contribute it to deathworlders.com but I don't see the code that produces the epubs in this repo. If nothing else I can give you the epub I made (mostly by hand but with 1 script to combine the chapter articles) and would be willing to update it as chapters come out. I feel like the epubs are useful if they can be read more than one chapter at a time.

**Comment by ctwelve** [comment]
Hello,

Take a look at deathworlders/kiera to see our theme modifications which perform the ePub generation. I've held off responding because we had a big changeset we had to publish, and, well...writing...but I do appreciate your attention.

Take a look there and see what you think!

**Comment by ctwelve** [comment]
Yo. It's been a while, are you still interested?

**Comment by Erroneous1** [comment]
Yeah sorry don't think I'll have time for this.
